print("Throwing exception...")
raise Exception("This should cause the testing to fail")
